### ISSUE TITLE
哪里可以看到配置文件的说明以及推荐配置呢

### ISSUE THREAD

**Issue by LogicWhyStudio** [huangzworks/redis-3.0-annotated#10]

**Comment by huangzworks** [comment]
https://github.com/huangz1990/redis-3.0-annotated/blob/unstable/redis.conf

**Comment by lanjingyu** [comment]
我是看到这个过来的 https://github.com/chaopeng/redis-conf
以为有翻译和说明 https://github.com/huangz1990/redis-3.0-annotated/blob/unstable/redis.conf 这个和官方那个一样的呀 。。。他说这里翻译的比他那个好 但是这里没看到翻译的。。。

**Comment by JianJ** [comment]
这个我也不知道，我只是关注他一下，没做深处了解

2015-12-02 20:08 GMT+08:00 xiaopeng.me notifications@github.com:
