### ISSUE TITLE
source insight 下都是乱码

### ISSUE THREAD

**Issue by oikomi** [huangzworks/redis-3.0-annotated#2]
能不能出个专门的source insight阅读版本?

**Comment by huangzworks** [comment]
请修改你的 source insight 的编码，比如改为 UTF-8 。

**Comment by oikomi** [comment]
source insight 不支持UTF-8 ， 要用记事本等一个一个文件的转换

**Comment by huangzworks** [comment]
我也不清楚要怎样转换文件的编码，没办法帮忙，请你：
1. 换一个支持 UTF-8 的编辑器；
2. 你自己来转换源码的编码；
3. 等会转换的人出现。

**Comment by oikomi** [comment]
Right. Super clear.
