### ISSUE TITLE
向大家请教一下跳跃表插入节点函数中的两句代码的含义？

### ISSUE THREAD

**Issue by bwangelme** [huangzworks/redis-3.0-annotated#27]
大家好，我最近在阅读 Redis 3.0的代码，提交ID是48e24d54。

在跳跃表的插入函数`zskiplistNode *zslInsert(zskiplist *zsl, double score, robj *obj)`中，关于计算节点中level的`span`，有这样两句代码，[代码链接](https://github.com/huangz1990/redis-3.0-annotated/blob/unstable/src/t_zset.c#L282):

```
    x = zslCreateNode(level,score,obj);
    for (i = 0; i < level; i++) {
        x->level[i].forward = update[i]->level[i].forward;
        update[i]->level[i].forward = x;

        /* update span covered by update[i] as x is inserted here */
        //TODO: 这两句这个跨度是如何计算的，真的没太看懂
        x->level[i].span = update[i]->level[i].span - (rank[0] - rank[i]);
        update[i]->level[i].span = (rank[0] - rank[i]) + 1;
    }
```

关于计算`span`的后两句，我真的没看太懂，我知道`update`数组记录的是每一层中，插入新节点前的一个节点，`rank`数组记录的是头结点到`update`中记录的节点的 span 值的和，请问那个`rank[0] - rank[i]`是什么意思啊，真的没太懂，还请各位书友不吝赐教。

**Comment by bwangelme** [comment]
level[0]中的span应该总是1，这样才能解释`rank[0] - rank[i]`。我们可以举这样一个例子，

例如有节点A和B，在他们中间插入X，`(rank[0] - rank[i])`计算的就是A到X-1的距离，`update[i]->level[i].span`就是A到B的距离。`update[i]->level[i].span - (rank[0] - rank[i])`计算的就是B到X的距离。

`update[i]->level[i].span = (rank[0] - rank[i]) + 1`计算的是A到X-1在+1，表示的是A到X的距离。

计算距离的时候是 __左开右闭__。

刚刚才想通，语言有点混乱，感觉还是要画个图。:Laugh:

**Comment by dujuejue** [comment]
我刚刚把span的定义理解错了，然后翻到铁子的这个issue，一下找到自己的问题，刚刚最开始也一直没理解这两行代码
